-- =====================================================================
-- Shady backend — initial schema
-- PostgreSQL 16. All timestamps are TIMESTAMPTZ (UTC); display tz = Africa/Cairo.
-- =====================================================================

-- ---------------------------------------------------------------------
-- auth
-- ---------------------------------------------------------------------
CREATE TABLE admin_user (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                 VARCHAR(254) NOT NULL,
    password_hash         VARCHAR(100) NOT NULL,                 -- BCrypt
    failed_login_attempts INT          NOT NULL DEFAULT 0,
    locked_until          TIMESTAMPTZ,
    password_changed_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version               BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT ck_admin_user_failed_attempts CHECK (failed_login_attempts >= 0)
);
CREATE UNIQUE INDEX ux_admin_user_email ON admin_user (lower(email));

CREATE TABLE refresh_token (
    id             UUID        PRIMARY KEY,
    admin_user_id  BIGINT      NOT NULL REFERENCES admin_user (id) ON DELETE CASCADE,
    family_id      UUID        NOT NULL,                        -- rotation chain; reuse => revoke family
    token_hash     CHAR(64)    NOT NULL,                        -- SHA-256 hex of the random token
    issued_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at     TIMESTAMPTZ NOT NULL,
    revoked_at     TIMESTAMPTZ,
    replaced_by_id UUID        REFERENCES refresh_token (id) ON DELETE SET NULL,
    CONSTRAINT ux_refresh_token_hash UNIQUE (token_hash)
);
CREATE INDEX ix_refresh_token_family  ON refresh_token (family_id);
CREATE INDEX ix_refresh_token_user    ON refresh_token (admin_user_id);
CREATE INDEX ix_refresh_token_expires ON refresh_token (expires_at);

-- ---------------------------------------------------------------------
-- media
-- ---------------------------------------------------------------------
CREATE TABLE media (
    id                UUID         PRIMARY KEY,                 -- also the random storage folder name
    original_filename VARCHAR(255),                             -- sanitized, admin display only
    width             INT          NOT NULL,                    -- of the LARGE variant
    height            INT          NOT NULL,
    alt_ar            VARCHAR(255),
    alt_en            VARCHAR(255),
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_media_dimensions CHECK (width > 0 AND height > 0)
);

CREATE TABLE media_variant (
    media_id     UUID         NOT NULL REFERENCES media (id) ON DELETE CASCADE,
    variant      VARCHAR(10)  NOT NULL,
    storage_key  VARCHAR(255) NOT NULL,                         -- media/{uuid}/{variant}.webp
    content_type VARCHAR(50)  NOT NULL DEFAULT 'image/webp',
    width        INT          NOT NULL,
    height       INT          NOT NULL,
    size_bytes   BIGINT       NOT NULL,
    PRIMARY KEY (media_id, variant),
    CONSTRAINT ck_media_variant_variant CHECK (variant IN ('THUMB', 'MEDIUM', 'LARGE')),
    CONSTRAINT ux_media_variant_key UNIQUE (storage_key)
);

-- ---------------------------------------------------------------------
-- categories
-- ---------------------------------------------------------------------
CREATE TABLE category (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug          VARCHAR(140) NOT NULL,
    name_ar       VARCHAR(120) NOT NULL,
    name_en       VARCHAR(120) NOT NULL,
    display_order INT          NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT ux_category_slug UNIQUE (slug)
);
CREATE INDEX ix_category_display_order ON category (display_order);

-- ---------------------------------------------------------------------
-- products
-- ---------------------------------------------------------------------
CREATE TABLE product (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug           VARCHAR(140)  NOT NULL,
    name_ar        VARCHAR(120)  NOT NULL,
    name_en        VARCHAR(120)  NOT NULL,
    description_ar VARCHAR(10000),                              -- sanitized HTML (allowlist)
    description_en VARCHAR(10000),
    price_egp      NUMERIC(10, 2),                              -- NULL = "ask for price"
    availability   VARCHAR(20)   NOT NULL DEFAULT 'AVAILABLE',
    category_id    BIGINT        REFERENCES category (id) ON DELETE SET NULL,
    featured       BOOLEAN       NOT NULL DEFAULT FALSE,
    published      BOOLEAN       NOT NULL DEFAULT FALSE,
    published_at   TIMESTAMPTZ,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version        BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT ux_product_slug UNIQUE (slug),
    CONSTRAINT ck_product_price CHECK (price_egp IS NULL OR price_egp >= 0),
    CONSTRAINT ck_product_availability CHECK (availability IN ('AVAILABLE', 'SOLD_OUT', 'MADE_TO_ORDER'))
);
CREATE INDEX ix_product_published ON product (published, created_at DESC);
CREATE INDEX ix_product_featured  ON product (featured, created_at DESC) WHERE published;
CREATE INDEX ix_product_category  ON product (category_id) WHERE published;

CREATE TABLE product_image (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    media_id      UUID   NOT NULL REFERENCES media (id) ON DELETE RESTRICT,
    display_order INT    NOT NULL,
    CONSTRAINT ux_product_image_order UNIQUE (product_id, display_order) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT ux_product_image_media UNIQUE (product_id, media_id)
);
CREATE INDEX ix_product_image_media ON product_image (media_id);

-- ---------------------------------------------------------------------
-- events
-- ---------------------------------------------------------------------
CREATE TABLE event (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug           VARCHAR(160)  NOT NULL,
    title_ar       VARCHAR(150)  NOT NULL,
    title_en       VARCHAR(150)  NOT NULL,
    description_ar VARCHAR(10000),
    description_en VARCHAR(10000),
    starts_at      TIMESTAMPTZ   NOT NULL,
    ends_at        TIMESTAMPTZ,
    location_type  VARCHAR(10)   NOT NULL,
    location_ar    VARCHAR(255),                                -- venue / address (IN_PERSON)
    location_en    VARCHAR(255),
    location_url   VARCHAR(500),                                -- maps link or meeting link
    is_free        BOOLEAN       NOT NULL DEFAULT FALSE,
    price_egp      NUMERIC(10, 2),                              -- NULL + not free = "ask for price"
    cover_media_id UUID          REFERENCES media (id) ON DELETE SET NULL,
    status         VARCHAR(10)   NOT NULL DEFAULT 'DRAFT',
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    version        BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT ux_event_slug UNIQUE (slug),
    CONSTRAINT ck_event_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ENDED')),
    CONSTRAINT ck_event_location_type CHECK (location_type IN ('IN_PERSON', 'ONLINE')),
    CONSTRAINT ck_event_price CHECK (price_egp IS NULL OR price_egp >= 0),
    CONSTRAINT ck_event_free_no_price CHECK (NOT is_free OR price_egp IS NULL),
    CONSTRAINT ck_event_dates CHECK (ends_at IS NULL OR ends_at >= starts_at)
);
CREATE INDEX ix_event_status_starts ON event (status, starts_at);
CREATE INDEX ix_event_starts_at     ON event (starts_at);
CREATE INDEX ix_event_cover_media   ON event (cover_media_id);

CREATE TABLE event_image (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id      BIGINT NOT NULL REFERENCES event (id) ON DELETE CASCADE,
    media_id      UUID   NOT NULL REFERENCES media (id) ON DELETE RESTRICT,
    display_order INT    NOT NULL,
    CONSTRAINT ux_event_image_order UNIQUE (event_id, display_order) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT ux_event_image_media UNIQUE (event_id, media_id)
);
CREATE INDEX ix_event_image_media ON event_image (media_id);

-- ---------------------------------------------------------------------
-- site content (hero / about / gallery / footer)
-- ---------------------------------------------------------------------
CREATE TABLE content_section (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_key VARCHAR(20)  NOT NULL,
    title_ar    VARCHAR(200),
    title_en    VARCHAR(200),
    subtitle_ar VARCHAR(500),
    subtitle_en VARCHAR(500),
    body_ar     VARCHAR(20000),                                 -- sanitized HTML (allowlist)
    body_en     VARCHAR(20000),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version     BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT ux_content_section_key UNIQUE (section_key),
    CONSTRAINT ck_content_section_key CHECK (section_key IN ('HERO', 'ABOUT', 'GALLERY', 'FOOTER'))
);

CREATE TABLE content_section_image (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id    BIGINT       NOT NULL REFERENCES content_section (id) ON DELETE CASCADE,
    media_id      UUID         NOT NULL REFERENCES media (id) ON DELETE RESTRICT,
    caption_ar    VARCHAR(300),
    caption_en    VARCHAR(300),
    display_order INT          NOT NULL,
    CONSTRAINT ux_content_section_image_order UNIQUE (section_id, display_order) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX ix_content_section_image_media ON content_section_image (media_id);

INSERT INTO content_section (section_key) VALUES ('HERO'), ('ABOUT'), ('GALLERY'), ('FOOTER');

-- ---------------------------------------------------------------------
-- contact settings (singleton row) + social links
-- ---------------------------------------------------------------------
CREATE TABLE contact_settings (
    id                 SMALLINT     PRIMARY KEY DEFAULT 1,
    whatsapp_number    VARCHAR(20),                             -- digits only, intl format, e.g. 201201200208
    instagram_username VARCHAR(30),                             -- without '@'
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version            BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT ck_contact_settings_singleton CHECK (id = 1),
    CONSTRAINT ck_contact_settings_whatsapp CHECK (whatsapp_number IS NULL OR whatsapp_number ~ '^[1-9][0-9]{7,14}$'),
    CONSTRAINT ck_contact_settings_instagram CHECK (instagram_username IS NULL OR instagram_username ~ '^[A-Za-z0-9._]{1,30}$')
);
INSERT INTO contact_settings (id) VALUES (1);

CREATE TABLE social_link (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform      VARCHAR(20)  NOT NULL,
    url           VARCHAR(500) NOT NULL,                        -- https only (validated in DTO)
    display_order INT          NOT NULL DEFAULT 0,
    CONSTRAINT ck_social_link_platform CHECK (platform IN ('FACEBOOK', 'TIKTOK', 'YOUTUBE', 'X', 'PINTEREST', 'BEHANCE', 'EMAIL', 'WEBSITE', 'OTHER'))
);
CREATE INDEX ix_social_link_display_order ON social_link (display_order);

-- ---------------------------------------------------------------------
-- stats: anonymous, daily-aggregated contact-button clicks
-- (polymorphic item reference: rows are deleted by the service when the item is deleted)
-- ---------------------------------------------------------------------
CREATE TABLE contact_click_daily (
    item_type   VARCHAR(10) NOT NULL,
    item_id     BIGINT      NOT NULL,
    channel     VARCHAR(10) NOT NULL,
    day         DATE        NOT NULL,
    click_count BIGINT      NOT NULL DEFAULT 0,
    PRIMARY KEY (item_type, item_id, channel, day),
    CONSTRAINT ck_click_item_type CHECK (item_type IN ('PRODUCT', 'EVENT')),
    CONSTRAINT ck_click_channel   CHECK (channel IN ('WHATSAPP', 'INSTAGRAM')),
    CONSTRAINT ck_click_count     CHECK (click_count >= 0)
);
CREATE INDEX ix_contact_click_daily_day ON contact_click_daily (day);

-- ---------------------------------------------------------------------
-- audit log (append-only)
-- ---------------------------------------------------------------------
CREATE TABLE audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    actor       VARCHAR(254) NOT NULL,                          -- admin email, or attempted email for failed logins
    action      VARCHAR(30)  NOT NULL,
    entity_type VARCHAR(30),
    entity_id   VARCHAR(64),
    ip_address  VARCHAR(45),
    details     JSONB,
    CONSTRAINT ck_audit_log_action CHECK (action IN (
        'LOGIN_SUCCESS', 'LOGIN_FAILURE', 'ACCOUNT_LOCKED', 'LOGOUT', 'TOKEN_REUSE_DETECTED',
        'PASSWORD_CHANGED', 'CREATE', 'UPDATE', 'DELETE'))
);
CREATE INDEX ix_audit_log_occurred_at ON audit_log (occurred_at DESC);
CREATE INDEX ix_audit_log_action      ON audit_log (action, occurred_at DESC);
