import { useState } from 'react'
import './index.css'

const art=[
 {id:1,title:'جدارية لونا كافيه',type:'كافيهات',image:'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=1000&q=85',desc:'جدارية دافئة مستوحاة من رائحة القهوة والحكايات الصغيرة حول الطاولات.'},
 {id:2,title:'عالم الألوان',type:'حضانات',image:'https://images.unsplash.com/photo-1580136579312-94651dfd596d?auto=format&fit=crop&w=1000&q=85',desc:'رسوم مرحة وآمنة للأطفال، تحوّل الجدار إلى مساحة خيال وتعلّم.'},
 {id:3,title:'قهوة وفن',type:'كافيهات',image:'https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?auto=format&fit=crop&w=1000&q=85',desc:'تفاصيل بسيطة وبألوان هادئة تجعل المكان أدفأ وأقرب للناس.'},
 {id:4,title:'مدينة الأحلام',type:'حضانات',image:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1000&q=85',desc:'شخصيات وقصص مصوّرة تساعد الطفل على اكتشاف عالمه بابتسامة.'},]
const initialOffers=[
 {id:1,tag:'الأكثر طلبًا',title:'رسم جدارية كافيه',price:'ابتداءً من ٣٥٠٠ ج.م',text:'تصميم مخصص لمساحة الكافيه، من الفكرة وحتى آخر لمسة لون.'},
 {id:2,tag:'للأطفال',title:'باقة حضانة سعيدة',price:'ابتداءً من ٥٠٠٠ ج.م',text:'عالم كامل من الشخصيات والألوان المناسبة لمساحة حضانتك.'},
 {id:3,tag:'فعالية قريبة',title:'يوم الرسم المفتوح',price:'السبت ٢٨ سبتمبر',text:'ورشة رسم مباشرة في لونا كافيه. الأماكن محدودة والحجز مسبق.'},]

export default function App(){
 const [tab,setTab]=useState('home'),[gallery,setGallery]=useState(null),[booking,setBooking]=useState(null),[offers,setOffers]=useState(initialOffers),[admin,setAdmin]=useState(false)
 const [form,setForm]=useState({name:'',phone:'',email:'',whatsapp:'',request:''}),[newOffer,setNewOffer]=useState({title:'',price:'',text:'',tag:'عرض جديد'})
 const submit=e=>{e.preventDefault();alert('وصلنا طلبك يا '+form.name+' ✨ هنتواصل معاك قريبًا.');setBooking(null);setForm({name:'',phone:'',email:'',whatsapp:'',request:''})}
 const add=e=>{e.preventDefault();if(!newOffer.title)return;setOffers([{...newOffer,id:Date.now()},...offers]);setNewOffer({title:'',price:'',text:'',tag:'عرض جديد'})}
 return <main dir="rtl">
  <header className="topbar"><button className="brand" onClick={()=>setTab('home')}><span className="brand-mark">ش</span><span>شادي <i>ARTIST</i></span></button><nav><button className={tab==='home'?'active':''} onClick={()=>setTab('home')}>الرئيسية</button><button className={tab==='offers'?'active':''} onClick={()=>setTab('offers')}>العروض والفعاليات</button></nav><button className="admin-link" onClick={()=>setAdmin(!admin)}>{admin?'عرض الموقع':'لوحة شادي'} <span>↗</span></button></header>
  {admin?<section className="admin"><div className="admin-head"><p className="eyebrow">مساحة المبدع</p><h1>أهلًا شادي، خلّي الناس تعرف الجديد.</h1><p>أضف عرضًا أو فعالية جديدة وستظهر فورًا في صفحة العروض.</p></div><form className="admin-form" onSubmit={add}><label>العنوان<input value={newOffer.title} onChange={e=>setNewOffer({...newOffer,title:e.target.value})} placeholder="مثال: ورشة رسم للأطفال"/></label><label>السعر أو الموعد<input value={newOffer.price} onChange={e=>setNewOffer({...newOffer,price:e.target.value})} placeholder="مثال: الجمعة ١٧ أكتوبر"/></label><label>نوع البطاقة<input value={newOffer.tag} onChange={e=>setNewOffer({...newOffer,tag:e.target.value})}/></label><label className="wide">وصف مختصر<textarea value={newOffer.text} onChange={e=>setNewOffer({...newOffer,text:e.target.value})} placeholder="اكتب تفاصيل العرض أو الفعالية"/></label><button className="paint-button">نشر الآن <span>✦</span></button></form><div className="mini-offers">{offers.map(o=><article key={o.id}><small>{o.tag}</small><b>{o.title}</b><em>{o.price}</em></article>)}</div></section>:tab==='home'?<>
  <section className="hero"><div className="hero-copy"><p className="eyebrow">رسم يخلّي المكان يحكي</p><h1>مساحات عادية<br/><span>بروحٍ ملوّنة.</span></h1><p className="lead">أنا شادي، فنان جداريات بحوّل الكافيهات والحضانات لمساحات فيها بهجة وحكاية.</p><div className="hero-actions"><button className="paint-button" onClick={()=>setTab('offers')}>شوف العروض <span>↙</span></button><a href="#portfolio">اكتشف الشغل <b>↓</b></a></div></div><div className="hero-art"><div className="sun"/><div className="canvas"><div className="paint-stroke stroke-1"/><div className="paint-stroke stroke-2"/><div className="paint-stroke stroke-3"/><span>ART<br/>IS<br/>JOY</span></div><div className="brush">🖌️</div><div className="dot dot1"/><div className="dot dot2"/></div></section>
  <section className="intro"><div><span className="num">01</span><h2>رسم له شخصية<br/>زي المكان بالضبط.</h2></div><p>من أول اسكتش للفكرة، لحد ما الألوان تنبض على الحيطة — كل مشروع معمول عشان الناس تحسّ بيه، وتصوره، وتفتكره.</p><div className="chips"><span>كافيهات</span><span>حضانات</span><span>فعاليات</span></div></section>
  <section className="portfolio" id="portfolio"><div className="section-title"><div><p className="eyebrow">مختارات من الشغل</p><h2>كل حيطه ليها حكاية.</h2></div><p>اضغط على أي مشروع وشوف التفاصيل</p></div><div className="gallery-grid">{art.map((x,i)=><button className={'work work-'+i} key={x.id} onClick={()=>setGallery(x)}><img src={x.image} alt={x.title}/><span className="work-info"><small>{x.type}</small><strong>{x.title}</strong><i>اكتشف المشروع ↗</i></span></button>)}</div></section>
  <section className="contact"><div className="scribble">✺</div><p className="eyebrow">جاهز نلوّن المكان؟</p><h2>خلّي حيطتك<br/><span>تحكي حكايتك.</span></h2><a className="paint-button" href="https://wa.me/201000000000" target="_blank">كلّمني على واتساب <span>↙</span></a><div className="socials"><a href="https://instagram.com" target="_blank">Instagram</a><a href="https://facebook.com" target="_blank">Facebook</a><a href="https://wa.me/201000000000" target="_blank">WhatsApp</a></div></section>
 </>:<section className="offers"><div className="offers-head"><p className="eyebrow">فيه جديد دايمًا</p><h1>اختار تجربتك<br/><span>المُلوّنة.</span></h1><p>عروض للرسم في المساحات، وفعاليات تقدر تحجز مكانك فيها.</p></div><div className="offer-list">{offers.map((o,i)=><article className={'offer-card card-'+i} key={o.id}><div><small>{o.tag}</small><h2>{o.title}</h2><p>{o.text}</p></div><footer><b>{o.price}</b><button onClick={()=>setBooking(o)}>احجز / اطلب <span>↙</span></button></footer></article>)}</div></section>}
 {gallery&&<div className="overlay" onClick={()=>setGallery(null)}><div className="modal gallery-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setGallery(null)}>×</button><img src={gallery.image} alt={gallery.title}/><div><small>{gallery.type}</small><h2>{gallery.title}</h2><p>{gallery.desc}</p><button className="paint-button" onClick={()=>{setGallery(null);setBooking({title:gallery.title})}}>عايز حاجة شبهها <span>↙</span></button></div></div></div>}
 {booking&&<div className="overlay" onClick={()=>setBooking(null)}><form className="modal booking" onClick={e=>e.stopPropagation()} onSubmit={submit}><button type="button" className="close" onClick={()=>setBooking(null)}>×</button><p className="eyebrow">خطوة صغيرة للفن</p><h2>احجز مع شادي</h2><p>مهتم بـ <b>{booking.title}</b>؟ سيب بياناتك وهنكلمك.</p><div className="form-grid"><input required placeholder="الاسم بالكامل" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required type="tel" placeholder="رقم التليفون" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input required type="email" placeholder="البريد الإلكتروني" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input required type="tel" placeholder="رقم واتساب" value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value})}/><select required value={form.request} onChange={e=>setForm({...form,request:e.target.value})}><option value="">نوع الطلب</option><option>حجز فعالية</option><option>طلب جدارية كافيه</option><option>طلب رسم حضانة</option><option>استفسار آخر</option></select></div><button className="paint-button">إرسال الطلب <span>✦</span></button></form></div>}
 </main>
}
